### PR TITLE
add back test on windows, add auto check on every Monday 2 p.m

### PR DESCRIPTION
**Pull request by Jackhr-arch**
The self-test code I committed (in autotest.py) are not yet completed, I think you should check its reliability

### CODE REVIEW

**Comment by Jackhr-arch** [comment]
now you can release by push a tag
I haven`t test upload to PyPI, since I don`t have the account, you need to do it yourself

**Comment by MarvinTerry** [comment]
I left ```PYPI_API_TOKEN``` in the repository's secret.

I will push a tag named "1.0.2" now

**Comment by MarvinTerry** [comment]
Working in progress...

image

And I have absolutely no knowledge of GitHub Action, I'll try to keep up my bro.

**Comment by MarvinTerry** [comment]
Invalid author format, I'll try another way to put 2 names on it.

image

**Pull request merged**
