### PR TITLE
Add publish to PyPI

### PR DESCRIPTION
**Pull request by Jackhr-arch**
I just add this in the ci.yml and remove the old one
It should publish a release on both github and PyPI now.

I see that problem, and now I move my info to 'maintainer', it should work now

### CODE REVIEW

**Comment by MarvinTerry** [comment]
failed to publish

image

**Comment by MarvinTerry** [comment]
Seemed like the url was wrong
image

**Comment by Jackhr-arch** [comment]
comment 'repository_url' line in ci.yml and try again?

**Comment by MarvinTerry** [comment]
Successfully uploaded, a huge applause to you!!!!!!!!!!!
image

**Comment by MarvinTerry** [comment]
I'll repush it to 1.0.2, and delete failed releases

**Pull request merged**
