### PR TITLE
Add physics lab curriculum

### PR DESCRIPTION
**Pull request by Jackhr-arch**
Add one example, due to the limit I can not test it, but I think it should work.
Maybe you can format the output and combine it to the main curriculum.

### CODE REVIEW

**Comment by Jackhr-arch** [comment]
A new interactive cli is added. You can easily adjust it.

**Comment by MarvinTerry** [comment]
The physics exp curriculum tested okay, I thought putting it into a new function would be much better, merging it into the original code will surely make a big mess.

**Comment by Jackhr-arch** [comment]
You may not get my meaning. I mean replace the place and teacher of physics lab experiments when query the main one.

**Comment by Jackhr-arch** [comment]
I reconstructed the cli function due to a fatal problem.
``` python3
interface = [
    {
        'type': 'list',
        'name': 'init',
        'message': 'What do you want to do?',
        'choices': [
            'Login',
            'Exit'
        ]
    },
    {
        'type':'list',
        'name':'actions',
        'message':'What you want to do?',
        'choices':[
            'Bills',
            'Curriculum',
            'Rooms',
            'Exit'
        ]
    },
    {
        'type':'list',
        'name':'bills',
        'message':'Which your want?',
        'choices':[
            'Dormitory',
            'E-card',
            'Go Back'
        ]
    }
]
login_para = [
    {
        'type': 'input',
        'name': 'UID',
        'message': 'Your Uid:',
        # 'validate': PhoneNumberValidator
    },
    {
        'type': 'password',
        'name': 'PWD',
        'message': 'Your Pwd:'
    },
    {
        'type': 'input',
        'name': 'DATE',
        'message': 'Which time? [format:1970-01-01]'
    },
    {
        'type': 'confirm',
        'name': 'IsExit',
        'message': 'Wrong uid,pwd, try again?',
        'default': 'Ture'
    }
]

def __get_date():
    from PyInquirer import prompt
    answer = prompt(login_para[2])
    return answer['DATE']

def cli():
    def prompt(arg):
        from PyInquirer import prompt as _prompt#, Separator
        ret = _prompt(arg)
        if not len(ret):
            raise Exception('Do not click, use Enter')
        return ret
    #import prompt_toolkit

    #class PhoneNumberValidator(prompt_toolkit.validation.Validator):
    #    def validate(self, document):
    #        ok = re.match('', document.text)
    #        if not ok:
    #            raise prompt_toolkit.validation.ValidationError(
    #                message='Please enter a valid Uid',
    #                cursor_position=len(document.text))  # Move cursor to end
            
    answer = prompt(interface[0])
    if answer['init'] == 'Exit':
        return 0
    
    while 1:
        auth = prompt(login_para[:2])
        try:
            from . import HustPass
            HUSTpass = HustPass(auth['UID'], auth['PWD'])
            break
        except NameError:
            answer = prompt(login_para[3])
            if not answer['IsExit']:
                return -1
        except ConnectionRefusedError:
            print('HUSTPASS: Authentication failed')
            return -1
        
    while 1:
        answer = prompt(interface[1])
        if answer['actions'] == 'Exit':
            break
        if answer['actions'] == 'Bills':
            answer = prompt(interface[2])
            if answer['bills'] == 'Go Back':
                continue
            date = __get_date()
            if answer['bills'] == 'E-card':
                result = HUSTpass.QueryEcardBills(date)
            elif answer['bills'] == 'Dormitory':
                result = HUSTpass.QueryElectricityBills(date)
        elif answer['actions'] == 'Curriculum':
            date = __get_date()
            result = HUSTpass.QuerySchedules(date)
        elif answer['actions'] == 'Rooms':
            date = __get_date()
            result = HUSTpass.QueryFreeRooms(date)

        print(result)
        
    print('Cleaning...') # Useless, just for Experience
    return 0
```
Replace the cli function with it. I don't wanna make another pr again.

**Comment by MarvinTerry** [comment]
I'll try it this weekend, but I assume the code won't look elegant.

**Comment by Jackhr-arch** [comment]
Just add a lilttle check on the main curriculum output and replace the item with the physics curriculum when detected. I believe it won't cause much trouble.



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 7, 2023 23:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MarvinTerry/HustLogin] Add physics lab curriculum (PR #20)




 
I'll try it this weekend, but I assume the code won't look elegant.

**Pull request merged**
